# Generated by Django 5.1.6 on 2025-03-10 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitcompletion',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
